POST http://localhost:5000/cadastro HTTP/1.1
Host: localhost:5000
Content-Type: application/json
Content-Length: 89

{
  "login": "cristiano faria",
  "senha": "123456",
  "email": "cristianoaf81@hotmail.com"
}
