POST http://localhost:5000/hoteis/delta HTTP/1.1
Host: localhost:5000
Content-Length: 99
Content-Type: application/json

{
  "nome": "Delta Hotel",
  "estrelas": 4.2,
  "diaria": 320.2,
  "cidade": "Brazopolis MG"
}
