POST http://localhost:5000/hoteis/fox HTTP/1.1
Host: localhost:5000
Content-Type: application/json 
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY2MDMwMjE1MywianRpIjoiNDExODkzN2ItNjNmYy00NDUwLWI5NjktZWM5ZDMzYWEyZGI4IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MSwibmJmIjoxNjYwMzAyMTUzLCJleHAiOjE2NjAzMDMwNTN9.IgJyQdWbJIhDmVq7FQ4J-_loxKOwr5CgVj3Wp0PT7EQ
Content-Length: 99

{
  "nome": "Hotel fox", 
  "estrelas": 4.1, 
  "diaria": 320.2,
  "cidade": "Brazopolis MG"
}
